Bug Fix in DistributedMeterStore
When a meter fails to get added via ONOS app, instead of showing the reason for failure, it throws exception:
IllegalArgumentException: Class is not registered: org.onosproject.net.meter.MeterFailReason

This fix registers approprate class to eliminate the exception.

Change-Id: I34cf10e7644980c9b40c3d6d4a51f5a6969f2d95