Fix NoClassDefFoundError when execute dhcp-set-static-mapping
The exception occurs because dhcp maven-bundle-plugin does not
properly export StringCompleter class which is contained under
org.apache.karaf.shell.console.completer package.

Change-Id: I9120e1b5b874de94d759e9fee41dcc660f24d793