Required changes to support OF1.4, 1.5.
- OVS with OF1.4 passed `stc smoke` test
- OVS with OF1.5 still has issue
  As of OVS 2.5.0, OF1.5 mode responds with ill-formed of_meter_features_stats_reply
  org.projectfloodlight.openflow.exceptions.OFParseError: Wrong length: Expected=40(40), got=32
    at org.projectfloodlight.openflow.protocol.ver15.OFMeterFeaturesStatsReplyVer15$Reader.readFrom(OFMeterFeaturesStatsReplyVer15.java:281)

Change-Id: Ib78b9d92ecfb4bb667e24c4ee95bcd09aec160a6